name: static-analytics

on: ['push']

jobs:
  phpstan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
    - uses: php-actions/composer@v5
    - uses: php-actions/phpstan@v3
